# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-12 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(max_length=300)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
