# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(max_length=300)),
                ('views', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
