# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-29 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200219_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('th_crd', 'started a new thread:'), ('th_upd', 'updated a thread you are following:'), ('co_lik', 'liked your comment in'), ('co_rep', 'replied to your comment in'), ('us_men', 'mentioned you in a comment in'), ('us_fld', 'is now following you')], max_length=6),
        ),
    ]
