# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import image_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=image_app.models.image_upload_to),
        ),
    ]
