# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-01 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
