# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190701_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(blank=True, max_length=127),
        ),
    ]
