# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-04 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 2, 33, 20, 606158, tzinfo=utc)),
        ),
    ]
