# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-04 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190704_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
    ]
