# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-04 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190704_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
