# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-15 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190516_0043'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadFollowership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comment_time', models.DateTimeField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Thread')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='followers',
            field=models.ManyToManyField(through='threads.ThreadFollowership', to='accounts.UserProfile'),
        ),
    ]
