# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-12 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20191109_1726'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('unread', models.BooleanField(default=False)),
                ('first_comment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='reader',
            field=models.ManyToManyField(related_name='thread_activity', through='threads.ThreadActivity', to=settings.AUTH_USER_MODEL),
        ),
    ]
