# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20190516_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
