# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-12 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20191112_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='reader',
            new_name='readers',
        ),
    ]
