# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-15 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0003_thread_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='final_comment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='final_comment_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_thread', to=settings.AUTH_USER_MODEL),
        ),
    ]
