# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-15 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20190615_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='final_comment_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_thread', to=settings.AUTH_USER_MODEL),
        ),
    ]
