# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-13 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0004_auto_20191112_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='followers2',
            field=models.ManyToManyField(related_name='thread_following2', to=settings.AUTH_USER_MODEL),
        ),
    ]
