# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-17 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20190612_0153'),
        ('threads', '0005_auto_20190615_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadfollowership',
            name='final_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='threadfollowership',
            name='has_new_comment',
            field=models.BooleanField(default=False),
        ),
    ]
