# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20190617_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadfollowership',
            name='new_comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
