# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-13 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20191113_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='followers2',
            new_name='followers',
        ),
        migrations.RemoveField(
            model_name='threadactivity',
            name='first_comment_url',
        ),
        migrations.RemoveField(
            model_name='threadactivity',
            name='unread',
        ),
    ]
