# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-18 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190516_0043'),
        ('threads', '0007_threadfollowership_new_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='followers',
            field=models.ManyToManyField(related_name='thread_following', through='threads.ThreadFollowership', to='accounts.UserProfile'),
        ),
    ]
