# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-14 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_auto_20191113_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='followers',
            field=models.ManyToManyField(related_name='thread_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
