# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-18 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_auto_20190618_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
