# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-17 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_auto_20191114_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadactivity',
            options={'verbose_name_plural': 'Thread Activities'},
        ),
    ]
