# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-21 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_offset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0009_auto_20191117_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadFollowership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('new_comment_count', models.PositiveIntegerField(default=0)),
                ('first_new_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='thread',
            name='followers',
        ),
        migrations.AddField(
            model_name='threadfollowership',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Thread'),
        ),
        migrations.AddField(
            model_name='threadfollowership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
