# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-22 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20190612_0153'),
        ('threads', '0009_auto_20190618_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='starting_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_thread', to='comments.Comment'),
        ),
    ]
