# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-21 23:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0010_auto_20191122_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='followers',
            field=models.ManyToManyField(related_name='thread_following', through='threads.ThreadFollowership', to=settings.AUTH_USER_MODEL),
        ),
    ]
