# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_comment_is_starting_comment'),
        ('threads', '0011_threadrevision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadrevision',
            old_name='comment',
            new_name='thread',
        ),
        migrations.AddField(
            model_name='threadrevision',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threadrevision',
            name='starting_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_thread_revision', to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='threadrevision',
            name='title',
            field=models.TextField(),
        ),
    ]
