# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-24 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0011_thread_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadactivity',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='threadactivity',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='threadactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='readers',
        ),
        migrations.DeleteModel(
            name='ThreadActivity',
        ),
    ]
