# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-29 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_auto_20190624_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
