# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-02 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0013_thread_hidden_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='hidden_by',
        ),
    ]
