# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0015_auto_20200219_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='views',
        ),
    ]
