# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-31 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'added_moderator'), (1, 'removed_moderator'), (2, 'added_category'), (3, 'removed_category')]),
        ),
    ]
