# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-01 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_auto_20191124_0435'),
        ('comments', '0004_auto_20191122_0252'),
        ('moderation', '0002_auto_20191231_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='hidden_comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='hidden_threads',
            field=models.ManyToManyField(to='threads.Thread'),
        ),
    ]
