# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-01 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0004_auto_20191122_0252'),
        ('threads', '0012_auto_20191124_0435'),
        ('moderation', '0003_auto_20200101_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorevent',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='moderatorevent',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderatorevent',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threads.Thread'),
        ),
        migrations.AddField(
            model_name='moderatorevent',
            name='unhidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderatorevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'added_moderator'), (1, 'removed_moderator'), (2, 'added_category'), (3, 'removed_category'), (4, 'Make thread invisible'), (5, 'Make thread visible'), (6, 'Make comment invisible'), (7, 'Make comment visible')]),
        ),
    ]
