# Generated by Django 3.2.25 on 2025-12-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_auto_20200219_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
