# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-09 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=4000)),
                ('marked_message', models.TextField(blank=True, max_length=4000)),
                ('is_starting_comment', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('downvoters', models.ManyToManyField(related_name='downvoted_comments', to=settings.AUTH_USER_MODEL)),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='comment_mention', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('marked_message', models.TextField(blank=True, max_length=4000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='comments.Comment')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='comment_rev_mention', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
