# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-14 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20191109_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='offset',
            field=models.IntegerField(default=0),
        ),
    ]
