# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-02 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('comments', '0004_auto_20191122_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='categories.Category'),
            preserve_default=False,
        ),
    ]
