# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-10 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='children',
            field=models.ManyToManyField(related_name='_comment_children_+', to='comments.Comment'),
        ),
    ]
