# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-19 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvoters',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvoters',
        ),
    ]
