# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-11 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20190610_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='children',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
