# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-11 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_commentreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='child',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
