# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_commentrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrevision',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
    ]
