# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-12 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20190612_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrevision',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='comments.Comment'),
        ),
    ]
