# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20190612_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_starting_comment',
            field=models.BooleanField(default=False),
        ),
    ]
