# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-29 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0014_auto_20190629_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
