# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-30 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_comment_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='marked_message',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='commentrevision',
            name='marked_message',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
