# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-06 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0018_auto_20190706_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='voters',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvoters',
            field=models.ManyToManyField(related_name='downvoted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
