# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 22:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0019_auto_20190706_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='comment_mention', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentrevision',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='comment_rev_mention', to=settings.AUTH_USER_MODEL),
        ),
    ]
