# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import forum.attachments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0004_auto_20190515_1812'),
        ('accounts', '0002_auto_20190516_0043'),
        ('threads', '0002_auto_20190516_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=forum.attachments.models.upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('comments', models.ManyToManyField(to='comments.Comment')),
                ('thread', models.ManyToManyField(to='threads.Thread')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
