# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-09 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import forum.attachments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20191109_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=forum.attachments.models.MediaFileSystemStorage(), upload_to=forum.attachments.models.upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('md5sum', models.CharField(blank=True, max_length=36)),
                ('is_avatar', models.BooleanField(default=False)),
                ('is_orphaned', models.BooleanField(default=True)),
                ('comments', models.ManyToManyField(blank=True, to='comments.Comment')),
                ('threads', models.ManyToManyField(blank=True, to='threads.Thread')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
