# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_orphaned',
            field=models.BooleanField(default=True),
        ),
    ]
