# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachment_is_orphaned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
