# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-17 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_remove_attachment_threads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='url',
        ),
    ]
