# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-18 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_remove_attachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
