# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_auto_20190606_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
