# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-18 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import forum.attachments.models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_attachment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(upload_to=forum.attachments.models.upload_to),
        ),
    ]
