# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_attachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='md5sum',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
