# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-11 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_auto_20190606_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='thread',
            new_name='threads',
        ),
    ]
