# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0007_auto_20190611_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='threads',
            field=models.ManyToManyField(blank=True, null=True, to='threads.Thread'),
        ),
    ]
