# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0008_auto_20190701_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='threads',
            field=models.ManyToManyField(blank=True, to='threads.Thread'),
        ),
    ]
