# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-03 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0010_auto_20190703_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='userprofile',
            new_name='userprofiles',
        ),
    ]
