# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-04 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0011_auto_20190703_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='has_userprofile',
            field=models.BooleanField(default=False),
        ),
    ]
